Django/Proyecto/Repositorio/blog/apps/noticias/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='noticias'),
]

Django/Proyecto/Repositorio/blog/apps/usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registro', views.register, name='registro'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout')
]

Django/Proyecto/Repositorio/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='inicio'),
    path('nosotros', views.about, name='nosotros'),
    path('contacto', views.contact, name='contacto'),
    path('faq', views.faq, 'faq'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
]

Django/Proyecto/Repositorio/blog/apps/noticias/models.py
from django.db import models

# Create your models here.

Django/Proyecto/Repositorio/blog/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
	pass

Django/Proyecto/Repositorio/blog/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from .models import Usuario

class RegisterUserForm(UserCreationForm):
    username = forms.EmailField(label='Email', required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    first_name = forms.CharField(label='Nombre', required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}))
    last_name = forms.CharField(label='Apellido', required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}))
    password1 = forms.CharField(
        label='Contraseña', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'}), required=True)
    password2 = forms.CharField(
        label='Confirmar Contraseña', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirmar contraseña'}), required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'password1',
            'password2'
        ]

class LoginUserForm(AuthenticationForm):
    username = forms.EmailField(label='Email', required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Contraseña'
        }
    ))
    class Meta:
        fields = [
        'username',
        'password'
        ]

Django/Proyecto/Repositorio/blog/apps/noticias/views.py
from django.shortcuts import render
from .models import *

def index(request):
    ctx = {}
    ctx['samples'] = [1, 2, 3]
    return render(request, 'noticias/noticias.html', ctx)

Django/Proyecto/Repositorio/blog/apps/usuarios/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login as login_user, logout as log_out
from .forms import RegisterUserForm, LoginUserForm

def login(request):
    if request.user.is_authenticated:
        return redirect('inicio')
    ctx = {
        'form': LoginUserForm
    }
    if request.method == "POST":
        form = LoginUserForm(data = request.POST)
        if form.is_valid():
            user = authenticate(username = request.POST['username'], password = request.POST['password'])
            login_user(request, user)
            return redirect('inicio')
        else:
            return render(request, 'usuarios/login.html', { 'form': form })
    else:
        return render(request, 'usuarios/login.html', ctx)

def register(request):
    if request.user.is_authenticated:
        return redirect('inicio')
    if request.method == "POST":
        form = RegisterUserForm(data = request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(username = form.cleaned_data['username'], password = form.cleaned_data['password1'])
            login_user(request, user)
            return redirect('inicio')
        else :
            return render(request, 'usuarios/registro.html', { 'form': form })
    else:
        ctx = {
            'form': RegisterUserForm
        }
        return render(request, 'usuarios/registro.html', ctx)

def logout(request):
    if request.user.is_authenticated:
        log_out(request)
    return redirect('inicio')

Django/Proyecto/Repositorio/blog/blog/views.py
from django.shortcuts import render

def index(request):
    ctx = {}
    ctx['samples'] = [1, 2, 3]
    return render(request, 'home.html', ctx)

def about(request):
	return render(request, 'nosotros.html')

def contact(request):
	return render(request, 'contacto.html')

def faq(request):
	return render(request, 'nosotros.html')

Django/Proyecto/Repositorio/blog/templates/base.html
{% load static %}
<html>

<head>
    <title>Fundacion Amigos del Arte y Turismo</title>
    <link rel="icon" href="{% static 'favicon.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'inicio' %}"><img src="{% static 'img/logo1.png' %}" alt=""
                    height="70px"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'nosotros' %}">Quienes somos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'noticias' %}" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Noticias
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Más recientes</a></li>
                            <li><a class="dropdown-item" href="#">Más destacadas</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'noticias' %}">Todas las noticias</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container-fluid d-flex justify-content-end">
        <a class="nav-link dropdown-toggle" href="javascript:void(0);" id="navbarDropdown_profile" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-circle"></i>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown_profile">
            {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="#">Perfil</a></li>
            <li><a class="dropdown-item" href="#">Ajustes</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'login' %}">Iniciar sesión</a></li>
            <li><a class="dropdown-item" href="{% url 'registro' %}">Registrarse</a></li>
            {% endif %}
        </ul>
    </div>
    <div>
        {% block content %}

        {% endblock content %}
    </div>

    <footer class="px-4">
        <div class="row d-flex justify-content-evenly">
            <div class="col-3">
                <h5>Navegación</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="{% url 'inicio' %}" class="nav-link p-0 text-muted">Inicio</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'nosotros' %}" class="nav-link p-0 text-muted">Quienes somos</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'contacto' %}" class="nav-link p-0 text-muted">Contacto</a></li>
                    <li class="nav-item mb-2"><a href="#faq" class="nav-link p-0 text-muted">FAQs</a></li>
                </ul>
            </div>
            <div class="col-3">
                <h5>Noticias</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Categor&iacute;a 1</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Categor&iacute;a 2</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Categor&iacute;a 3</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Categor&iacute;a 4</a></li>
                </ul>
            </div>
            <div class="col-4 offset-1">
                {% if user.is_authenticated %}
                <div>
                    <div class="h3">Gracias por formar parte!</div>
                </div>
                {% else %}
                <form>
                    <h5>Suscr&iacute;bete a nuestro noticiasletter</h5>
                    <p>Recibe noticias mensualmente!</p>
                    <div class="d-flex w-100 gap-2">
                        <label for="noticiasletter1" class="visually-hidden">Email address</label>
                        <input id="noticiasletter1" type="text" class="form-control" placeholder="Email address">
                        <button class="btn btn-primary" type="button">Subscribe</button>
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
        <div class="d-flex flex-wrap justify-content-between align-items-center py-3 m-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="{% url 'inicio' %}" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <img src="{% static 'favicon.png' %}" alt="Logo - Fundacion amigos del arte y turismo"
                        height="24px">
                </a>
                <span class="text-muted">© 2021 Fundacion Amigos del Arte y Turismo</span>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3">
                    <a class="text-muted" href="#">
                        <i class="bi bi-envelope-at-fill"></i>
                    </a>
                </li>
                <li class="ms-3"><a class="text-muted" href="#">
                        <i class="bi bi-instagram"></i>
                    </a>
                </li>
                <li class="ms-3">
                    <a class="text-muted" href="#">
                        <i class="bi bi-facebook"></i>
                    </a>
                </li>
            </ul>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>

</html>

Django/Proyecto/Repositorio/blog/templates/contacto.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="m-4">
    <form class="p-4 shadow p-3 mb-5 bg-body rounded border-1" style="max-width: 500px; margin: auto;">
        <div class="mb-3">
            <label for="nameInput" class="form-label">Nombre y apellido</label>
            <input placeholder="Nombre y apellido" type="text" class="form-control" id="nameInput" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Correo electrónico</label>
            <input placeholder="Correo electrónico" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="textarea1" class="form-label">D&eacute;janos tu mensaje</label>
            <textarea placeholder="D&eacute;janos tu mensaje" class="form-control" name="message" id="textarea1" cols="30" rows="5"></textarea>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Suscribirse a nuestro noticiasletter</label>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</div>
{% endblock content %}

Django/Proyecto/Repositorio/blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="carouselExampleDark" class="carousel carousel-dark slide m-4" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
            <img src="static/img/imp1.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h3 class="text-white">
                    Nuestra meta es promover el Arte y el Turismo, rescatando, revalorizando e incluyendo todas las
                    manifestaciones artísticas y culturales, en salvaguarda de nuestra identidad, y en defensa del medio
                    ambiente
                </h3>
            </div>
        </div>
        <div class="carousel-item" data-bs-interval="2000">
            <img src="static/img/imp2.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h2 class="text-white">
                    La Fundación Amigos del Arte y Turismo, con Personería Jurídica Nº452/14 es una Entidad no
                    lucrativa, con el fin de vincular las expresiones culturales de la región, la idiosincrasia de la
                    gente y el turismo a través del ARTE
                </h2>
            </div>
        </div>
        <div class="carousel-item">
            <img src="static/img/imp3.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h2 class="text-white">
                    Nos reconocemos como parte de “El Impenetrable”, su cultura y su gente. Por eso, buscamos dar a
                    conocer nuestra región, su riqueza, sus leyendas, su arte y su poesía, que invitan a recorrer
                    lugares como la FIDELIDAD, MISIÓN NUEVA POMPEYA, LA CANGAYÉ, LAS RUINAS DEL Km 71 que nos hablan de
                    nuestra historia y nuestra gente.
                </h2>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<div class="m-4 p-4">
    <div class="h1">Todas las noticias</div>
    <div class="card-group gap-3">
        {% for n in samples %}
        <div class="card box-shadow-3">
            <img src="{% static 'img/imp1.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Titulo de la noticia</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional
                    content. This content is a little bit longer.</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

Django/Proyecto/Repositorio/blog/templates/nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="db-main order-1 m-4 p-4">
    <div class="my-3 p-3">
        <div class="h1">Qui&eacute;nes somos</div>
        <div class="bd-lead">
            La Fundación Amigos del Arte y Turismo, con Personería Jurídica Nº452/14 es una Entidad no lucrativa, con el
            fin
            de vincular las expresiones culturales de la región, la idiosincrasia de la gente y el turismo a través del
            ARTE.
            Nuestra meta es promover el Arte y el Turismo, rescatando, revalorizando e incluyendo todas las
            manifestaciones
            artísticas y culturales, en salvaguarda de nuestra identidad, y en defensa del medio ambiente.
            Geográficamente ubicados en el Departamento General Güemes de la provincia del Chaco, en la Puerta del
            Impenetrable, con una comunidad integrada por pueblos originarios de distintas etnias, criollos y
            descendientes
            de inmigrantes de distintos países de Europa.
            Nos reconocemos como parte de “El Impenetrable”, su cultura y su gente. Por eso, buscamos dar a conocer
            nuestra
            región, su riqueza, sus leyendas, su arte y su poesía, que invitan a recorrer lugares como la FIDELIDAD,
            MISIÓN
            NUEVA POMPEYA, LA CANGAYÉ, LAS RUINAS DEL Km 71 que nos hablan de nuestra historia y nuestra gente.

        </div>
    </div>
    <div class="my-3 p-3">
        <div class="h1">Nuestra misi&oacute;n</div>
        <div class="">
            Ser partícipes del desarrollo cultural, brindar oportunidades y capacitación del Arte y hacer del mismo un
            atractivo turístico.
        </div>
    </div>
    <div class="my-3 p-3">
        <div class="h1">Nuestra visi&oacute;n</div>
        <div class="">
            Sacar a la luz lo que late en el Impenetrable.
        </div>
    </div>
    <div class="my-3 p-3">
        <div class="h1">Objetivos Generales</div>
        <div class="">
            <ul>
                <li>Velar por nuestro rico patrimonio cultural y dar a conocer a todos los que nos visiten las
                    diferentes expresiones de nuestra identidad.
                </li>
                <li>Estimular y divulgar el arte y el turismo y fomentarlos como fuente de superación de las personas de
                    nuestra comunidad y darlo a conocer.
                </li>
            </ul>
        </div>
    </div>
    <div class="my-3 p-3">
        <div class="h1">Objetivos Espec&iacute;ficos</div>
        <div class="">
            <ul>
                <li>
                    Organizar eventos de cualquier naturaleza con carácter regional, nacional e internacional en pro del
                    desarrollo del arte y el turismo.
                </li>
                <li>
                    Impulsar el turismo revitalizando las artes tradicionales y la industria artesanal de la zona a
                    través de la comercialización de los productos locales y de otros recursos de aquellas localidades
                    marginadas por la desindustrialización o el aislamiento.
                </li>
                <li>
                    Proteger y restaurar nuestro patrimonio cultural y artístico.
                </li>
                <li>
                    Organizar encuentros culturales, espectáculos y otros acontecimientos que contribuyan a divulgar
                    nuestra idiosincrasia.
                </li>
                <li>
                    Desarrollar programas de formación y capacitación que estén íntimamente relacionados con la misión
                    de la fundación.
                </li>
                <li>
                    Generar muestras públicas de contemplación de técnicas y observación de creación de obras artísticas
                    celebrando exposiciones temáticas con artistas invitados.
                </li>
                <li>
                    Generar muestras públicas de contemplación de técnicas y observación de creación de obras artísticas
                    celebrando exposiciones temáticas con artistas invitados.
                </li>
                <li>
                    Ayudar y colaborar en proyectos públicos o privados en los que se combinen cultura y turismo (rutas
                    literarias, rutas históricas, etc.) con mayor intensidad en lo que se refiere a la colaboración
                    recíproca con otras Fundaciones culturales o de otros fines que coadyuven en la promoción de la
                    cultura.
                </li>
                <li>
                    Apoyar proyectos educativos, culturales destinados a destacar la importancia de la cultura.
                </li>
                <li>
                    Desarrollar e impulsar el turismo interior en el Impenetrable en sintonía con la tendencia en alza
                    del turismo alternativo (cultura y naturaleza).
                </li>
                <li>
                    Promover actividades de formación en el conocimiento de la cultura.
                </li>
                <li>
                    Potenciar Castelli y su región como destino turístico.
                </li>
            </ul>
        </div>
    </div>
    <div class="my-3 p-3">
        <div class="h1">Conformación de la actual comisi&oacute;n</div>
        <div class="bd-lead">
            <ul>
                <li><b>Presidente</b>: DG. Rene Bertolucci</li>
                <li><b>Vicepresidente</b>: Arq. Yolanda M. Rausch</li>
                <li><b>Secretaria</b>: Prof. Marisa Santamaría</li>
                <li><b>Tesorera</b>: Prof. Elena Díaz de Lázara</li>
                <li><b>Vocal</b>: Dr. Jorge Kleisinger</li>
            </ul>
        </div>
    </div>
    <div class="my-3 p-3">
        <div class="h1">Ubicación</div>
        <div>
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d896.9209838284005!2d-60.6207856!3d-25.9456008!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94404cfba5224f0b%3A0xbe1797f5f1777f83!2sFundaci%C3%B3n%20Amigos%20del%20Arte%20y%20Turismo!5e0!3m2!1ses!2sar!4v1669693704333!5m2!1ses!2sar"
                width="100%" height="200" style="border:0;" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</div>
{% endblock content%}

Django/Proyecto/Repositorio/blog/templates/noticias/noticias.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="m-4 p-4">
    <div class="h1">Todas las noticias</div>
    <div class="card-group gap-3">
        {% for n in samples %}
        <div class="card box-shadow-3">
            <img src="{% static 'img/imp1.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Titulo de la noticia</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional
                    content. This content is a little bit longer.</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="m-4 p-4">
    <div class="h1">Noticias destacadas</div>
    <div class="card-group gap-3">
        {% for n in samples %}
        <div class="card">
            <img src="{% static 'img/imp1.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Titulo de la noticia</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional
                    content. This content is a little bit longer.</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Last updated 3 mins ago</small>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

Django/Proyecto/Repositorio/blog/templates/usuarios/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="m-4">
    <form class="p-4 shadow p-3 mb-5 bg-body rounded border-1" style="max-width: 500px; margin: auto;" method="post">
        {%csrf_token%}
        <div class="h1">Iniciar sesión</div>
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            Por favor, ingrese un usuario y contraseña correctos

  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        <div class="mbs-3">
            <label for="id_email" class="form-label">Correo electrónico</label>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label for="id_password" class="form-label">Contraseña</label>
            {{form.password}}
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Guardar sesión</label>
        </div>
        <button type="submit" class="btn btn-primary">Iniciar</button> | <a href="{% url 'registro' %}">Registrarse</a>
    </form>
</div>
{% endblock content %}

Django/Proyecto/Repositorio/blog/templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="m-4">
    <form class="p-4 shadow p-3 mb-5 bg-body rounded border-1" style="max-width: 500px; margin: auto;" method="post">
        {% csrf_token %}
        <div class="h1">Registrarse</div>
        <div class="mb-3">
            <label for="id_first_name" class="form-label">Nombre</label>
            {{form.first_name}}
            <div class="text-danger">
                {{form.first_name.errors}}
            </div>
        </div>
        <div class="mb-3">
            <label for="id_last_name" class="form-label">Apellido</label>
            {{form.last_name}}
            <div class="text-danger">
                {{form.last_name.errors}}
            </div>
        </div>
        <div class="mb-3">
            <label for="id_email" class="form-label">Correo electrónico</label>
            {{form.username}}
            <div class="text-danger">
                {{form.username.errors}}
            </div>
        </div>
        <div class="mb-3">
            <label for="id_password1" class="form-label">Contraseña</label>
            {{form.password1}}
            <div class="danger">
                {{form.password1.errors}}
            </div>
        </div>
        <div class="mb-3">
            <label for="id_password2" class="form-label">Confirmar contraseña</label>
            {{form.password2}}
            <div class="text-danger">
                {{form.password2.errors}}
            </div>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Suscribirse a nuestro newsletter</label>
        </div>
        <button type="submit" class="btn btn-primary">Crear usuario</button> | <a href="{% url 'login' %}">Ya tengo una
            cuenta</a>
    </form>
</div>
{% endblock content %}